Departments Tab Implemented
ITPNYU/booking-app pull request #298
Opened 2024-08-02 19:26 UTC by Kaibanda

Departments can be added with an assigned tier on the departments tab.

2024-08-03 22:00 UTC, lucia-gomez requested changes
Thanks for doing this, it looks great and follows our existing code structure!

One thing to improve: I see you created a new component `AddDepartmentRow` to use instead of `AddRow`. This was a good call because the add department form needs 2 dropdowns and no text field, making it different from `AddRow`. 

But since `AddDepartmentRow` is a very specific component not meant to be reused, could you make it less general? There's no need to keep it similar to `AddRow` with all the props, you can just hardcode the department-specific UI directly in your new component (ex: don't pass in the dropdowns via `props.extra.components`. I think this will the component easier to understand

2024-08-07 15:29 UTC, Kaibanda commented
I have made the suggested changes. Let me know if this looks good. Thank you.

2024-08-07 21:35 UTC, Kaibanda commented
Hello Lucia, I have requested you as a reviewer again, as I have made another commit to this branch without the props.extra fields. I also removed the comments that you mentioned, and un-commented some of the logic that you will be re-factoring. Thank you.

2024-08-11 00:17 UTC, lucia-gomez approved these changes

2024-08-11 00:18 UTC, merged